name: setup
inputs:
  haxe:
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: install haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: ${{ inputs.haxe }}

    - name: install haxe libraries
      shell: pwsh
      run: |
        haxelib install utest
        haxelib git hx4compat https://github.com/HaxeFoundation/hx4compat
        haxelib dev hxcpp ${{ github.workspace }}
        haxelib list

    - name: build run.n
      working-directory: tools/run
      shell: pwsh
      run: haxe compile.hxml

    - name: build hxcpp
      working-directory: tools/hxcpp
      shell: pwsh
      run: haxe compile.hxml