name: setup
inputs:
  haxe:
    required: true
    type: string
  hxcpp:
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: install haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: ${{ inputs.haxe }}

    - name: install haxe libraries
      shell: bash
      run: |
        set -ex
        haxelib install utest
        haxelib git hx4compat https://github.com/HaxeFoundation/hx4compat
        haxelib dev hxcpp ${{ inputs.hxcpp }}
        haxelib list

    - name: install native libraries
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get install -qqy gcc-multilib g++-multilib

    - name: build run.n
      working-directory: tools/run
      shell: bash
      run: haxe compile.hxml

    - name: build hxcpp
      working-directory: tools/hxcpp
      shell: bash
      run: haxe compile.hxml