name: build
on:
  workflow_call:
    inputs:
      haxe:
        required: true
        type: string

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - arch: 64
          - arch: 32
            os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ inputs.haxe }}

      - name: Check
        run: haxe --version

      # - name: Haxe
      #   working-directory: test/haxe 
      #   run: |
      #     haxe compile.hxml --debug -D HXCPP_M${{ matrix.arch }}
      #     bin/TestMain-debug

      # - name: Telemetry
      #   run: haxe

      # - name: Std
      #   run: haxe

      # - name: Debugger
      #   run: haxe

      # - name: Native
      #   run: haxe

      # - name: Haxe Unit Tests
      #   run: haxe