name: test
on:
  workflow_call:
    inputs:
      haxe:
        required: true
        type: string

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
        arch: [ 64 ]
        include:
          - os: ubuntu-latest
            arch: 32
          - os: windows-latest
            arch: 32
          - os: ubuntu-latest
            lib-ext: .dso
            sep: '/'
          - os: macos-13
            lib-ext: .dylib
            sep: '/'
          - os: windows-latest
            lib-ext: .dll
            sep: '\'
    runs-on: ${{ matrix.os }}
    name: test ${{ matrix.os }} (${{ matrix.arch }}bit)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ inputs.haxe }}

      ## Dependency Setup
      - name: Install MariaDB
        if: runner.os == 'Linux'
        run: |
          set -ex
          sudo rm -R /var/lib/mysql/
          # mariadb
          curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup > mariadb_repo_setup
          curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup.sha256 > mariadb_repo_setup.sha256
          sha256sum --check mariadb_repo_setup.sha256
          sudo bash mariadb_repo_setup
          sudo apt-get update -qqy
          sudo apt-get remove -qqy mysql-common
          sudo apt-get autoremove -qqy
          sudo apt-get install -qqy mariadb-server
          # remaining packages
          sudo apt-get install -qqy gcc-multilib g++-multilib

      - name: Configure MariaDB
        if: runner.os == 'Linux'
        run: |
          set -ex
          sudo systemctl start mysql
          sudo mysql -u root -e "create database hxcpp; grant all privileges on hxcpp.* to hxcpp@localhost identified by 'hxcpp'; flush privileges;"

      - name: Install Haxe Libraries
        run: |
          haxelib install utest
          haxelib git hx4compat https://github.com/HaxeFoundation/hx4compat
          haxelib dev hxcpp ${{ github.workspace }}
          haxelib list

      - name: Build run.n
        run: |
          cd ${{ github.workspace }}/tools/run
          haxe compile.hxml

      - name: Build Hxcpp
        run: |
          cd ${{ github.workspace }}/tools/hxcpp
          haxe compile.hxml

      - name: Build Cppia
        run: |
          cd ${{ github.workspace }}/project
          haxe compile-cppia.hxml

      ## Haxe
      - name: haxe test - compile
        run: |
          cd ${{ github.workspace }}/test/haxe
          haxe compile.hxml --debug -D HXCPP_M${{ matrix.arch }}

      - name: haxe test - run
        run: |
          cd ${{ github.workspace }}/test/haxe
          bin${{ matrix.sep }}TestMain-debug

      # - name: Haxe
      #   working-directory: test/haxe 
      #   run: |
      #     haxe compile.hxml --debug -D HXCPP_M${{ matrix.arch }}
      #     bin/TestMain-debug

      # - name: Telemetry
      #   run: haxe

      # - name: Std
      #   run: haxe

      # - name: Debugger
      #   run: haxe

      # - name: Native
      #   run: haxe

      # - name: Haxe Unit Tests
      #   run: haxe