name: test-expander
on:
  workflow_call:
    inputs:
      haxe:
        required: true
        type: string

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
        arch: [ 32, 64 ]
        exclude:
          # Remove 32bit variants for Mac
          - os: macos-13
            arch: 32
        include:
          # Add some extra OS specific variables
          - sep: '/'
          - sep: '\'
            os: windows-latest
          - ext: '.dso'
            os: ubuntu-latest
          - ext: '.dylib'
            os: macos-13
          - ext: '.dll'
            os: windows-latest
    name: test ${{ matrix.os }} (${{ matrix.arch }}bit)
    uses: ./.github/workflows/test.yml
    with:
      haxe: ${{ inputs.haxe }}
      arch: ${{ matrix.arch }}
      sep: ${{ matrix.sep }}
      ext: ${{ matrix.ext }}
      os: ${{ matrix.os }}

    #   ## Haxe Unit Tests
    #   - name: haxe unit test - clone haxe repo
    #     uses: actions/checkout@v4
    #     with:
    #       repository: HaxeFoundation/haxe
    #       path: haxe
    #       fetch-tags: true
    #   - name: haxe unit test - switch haxe repo
    #     if: inputs.haxe != 'latest'
    #     run: |
    #       cd ${{ github.workspace }}/haxe
    #       git switch ${{ inputs.haxe }} --detach
    #   - name: haxe unit test - install haxelib
    #     run: |
    #       cd ${{ github.workspace }}/haxe/tests/unit
    #       haxelib install compile-cpp.hxml --always
    #   - name: haxe unit test - compile
    #     run: |
    #       cd ${{ github.workspace }}/haxe/tests/unit
    #       haxe compile-cpp.hxml -D HXCPP_M${{ matrix.arch }} -D no_http
    #   - name: haxe unit test - run
    #     run: |
    #       cd ${{ github.workspace }}/haxe/tests/unit
    #       bin${{ matrix.sep }}cpp${{ matrix.sep }}TestMain-debug