name: test
on:
  workflow_call:
    inputs:
      haxe:
        required: true
        type: string

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
        arch: [ 64 ]
        include:
          - os: ubuntu-latest
            arch: 32
          - os: windows-latest
            arch: 32
    runs-on: ${{ matrix.os }}
    name: test ${{ matrix.os }} (${{ matrix.arch }}bit)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ inputs.haxe }}

      - name: Install Haxe Libraries
        run: |
          haxelib install utest
          haxelib git hx4compat https://github.com/HaxeFoundation/hx4compat
          haxelib dev hxcpp ${{ github.workspace }}
          haxelib list

      - name: Build run.n
        run: |
          cd ${{ github.workspace }}/tools/run
          haxe compile.hxml

      - name: Build Hxcpp
        run: |
          cd ${{ github.workspace }}/tools/hxcpp
          haxe compile.hxml

      - name: Build Cppia
        run: |
          cd ${{ github.workspace }}/project
          haxe compile-cppia.hxml

      # - name: Haxe
      #   working-directory: test/haxe 
      #   run: |
      #     haxe compile.hxml --debug -D HXCPP_M${{ matrix.arch }}
      #     bin/TestMain-debug

      # - name: Telemetry
      #   run: haxe

      # - name: Std
      #   run: haxe

      # - name: Debugger
      #   run: haxe

      # - name: Native
      #   run: haxe

      # - name: Haxe Unit Tests
      #   run: haxe